### ISSUE TITLE
Look into why manipulations give back missings

### ISSUE THREAD

**Issue by gergelyattilakiss** [codedthinking/Kezdi.jl#63] opened 2024-06-25 08:52 UTC
Sometimes it seems that manipulations with columns with `type` gives back `type?`.

**Comment by gergelyattilakiss** [comment] 2024-06-26 11:57
There are sure no missings in the df after running it. So it might be some default behavior?
![image](https://github.com/codedthinking/Kezdi.jl/assets/47605029/88d4d594-f027-42ba-b384-c69c373bf6c1)

**Comment by gergelyattilakiss** [comment] 2024-06-26 11:57
Transform does not have this...
![image](https://github.com/codedthinking/Kezdi.jl/assets/47605029/6bb6dc3e-8e3e-4c6f-848b-a8d669204dea)

**Comment by gergelyattilakiss** [comment] 2024-06-26 11:59
Also, pandas like indexing approach does not have this. 
![image](https://github.com/codedthinking/Kezdi.jl/assets/47605029/a491ce8b-c471-41c3-bfff-c8a9d91042a9)

**Comment by gergelyattilakiss** [comment] 2024-06-26 12:07
Not view creation is at fault.
![image](https://github.com/codedthinking/Kezdi.jl/assets/47605029/0aedd485-0d77-4bd7-a577-6abee426cbdf)

**Comment by gergelyattilakiss** [comment] 2024-06-26 12:58
I think I have where we introduce the missing type into the workflow.
Using `df.x+df.y' in an assingment on SubDataFrames causes this. I check in the related package if this is intentional.

**Comment by gergelyattilakiss** [comment] 2024-06-26 13:14
Further checks show that `sdf` level definition causes the `missing` type inclusion. Another thing that comes is if something is created in a `df` it flows down to `sdf`.

**Comment by korenmiklos** [comment] 2024-06-26 16:47
Wow, this is deep. 

It is indeed the expected behavior. If you assign some values to a SubDataFrame, the rest of the dataframe may be missing. 

We do this manually by creating a fully missing vector first. But maybe not even needed.

**Comment by korenmiklos** [comment] 2024-06-26 16:48
Because this works as expected, closing as wontfix.

**Closed** 2024-06-26 16:48 UTC
Labels: bug
